version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18.16.0-browsers # Use a Node.js image with browsers if tests involve UI

jobs:
  build:
    executor: node-executor
    steps:
      - checkout # Check out the code
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build Application
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: circleci/python:3.9 # Optional Python image if SSH or deployment scripts use Python
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Deploy to Server
          command: |
            scp -r /workspace/build ubuntu@<YOUR_SERVER_IP>:/home/ubuntu/feature-4/
            ssh ubuntu@<YOUR_SERVER_IP> 'sudo systemctl restart nginx'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

